version: "3.8"

services:
    zookeeper:
      image: confluentinc/cp-zookeeper:latest
      container_name: zookeeper
      ports:
        - 2181:2181
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
      restart: always

    kafka:    
      image: confluentinc/cp-kafka
      container_name: kafka
      ports:
        - 9093:9093
        - 9094:9094
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,HOST://kafka:9093,OUTSIDE://127.0.0.1:9094
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT,HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
        KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true" 
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_LOG_RETENTION_HOURS: 24
        KAFKA_LOG_RETENTION_BYTES: 1073741824 #1GB
      depends_on:
        - zookeeper
      restart: always

    kafka-ui:
      container_name: kafka-ui
      image: provectuslabs/kafka-ui:latest
      ports:
        - 9999:8080
      depends_on:
        - zookeeper
        - kafka
      environment:
        KAFKA_CLUSTERS_0_NAME: local
        KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
        KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
        KAFKA_CLUSTERS_0_JMXPORT: 9997
        KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schemaregistry:8085
        KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: ATCLL
        KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect:8083

